name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Install dependencies
      working-directory: src
      run: |
        go get github.com/mr-tron/base58/base58
        go get github.com/pkoukk/tiktoken-go
        go mod tidy

    - name: Build for Linux (x64)
      working-directory: src
      run: GOOS=linux GOARCH=amd64 go build -o ../gitingest-linux-x64 gitingestgo.go

    - name: Build for Linux (arm64)
      working-directory: src
      run: GOOS=linux GOARCH=arm64 go build -o ../gitingest-linux-arm64 gitingestgo.go

    - name: Build for macOS (x64)
      working-directory: src
      run: GOOS=darwin GOARCH=amd64 go build -o ../gitingest-macos-x64 gitingestgo.go

    - name: Build for macOS (arm64)
      working-directory: src
      run: GOOS=darwin GOARCH=arm64 go build -o ../gitingest-macos-arm64 gitingestgo.go

    - name: Build for Windows (x64)
      working-directory: src
      run: GOOS=windows GOARCH=amd64 go build -o ../gitingest-windows-x64.exe gitingestgo.go

    - name: Build for Windows (arm64)
      working-directory: src
      run: GOOS=windows GOARCH=arm64 go build -o ../gitingest-windows-arm64.exe gitingestgo.go

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Linux x64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gitingest-linux-x64
        asset_name: gitingest-linux-x64
        asset_content_type: application/octet-stream

    - name: Upload Linux arm64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gitingest-linux-arm64
        asset_name: gitingest-linux-arm64
        asset_content_type: application/octet-stream

    - name: Upload macOS x64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gitingest-macos-x64
        asset_name: gitingest-macos-x64
        asset_content_type: application/octet-stream

    - name: Upload macOS arm64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gitingest-macos-arm64
        asset_name: gitingest-macos-arm64
        asset_content_type: application/octet-stream

    - name: Upload Windows x64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gitingest-windows-x64.exe
        asset_name: gitingest-windows-x64.exe
        asset_content_type: application/octet-stream

    - name: Upload Windows arm64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gitingest-windows-arm64.exe
        asset_name: gitingest-windows-arm64.exe
        asset_content_type: application/octet-stream